#!/usr/bin/env php
<?php
define('APPLICATION_PATH', dirname(__FILE__));
$classLoader = require(APPLICATION_PATH . '/vendor/autoload.php');
$classLoader->setPsr4('ReInit\\', APPLICATION_PATH . '/library/ReInit/');
$classLoader->setPsr4('Royal\\', APPLICATION_PATH . '/library/Royal/');
$classLoader->setPsr4('Truesign\\', APPLICATION_PATH . '/common');
$classLoader->setPsr4('Server\\', APPLICATION_PATH . '/server');

define('MODEL_PATH',APPLICATION_PATH.'/application/models');
define('TEMPLATE_PATH',APPLICATION_PATH.'/library/Royal/InitCommand/templates');

$application = new \Symfony\Component\Console\Application();

// ... register commands

$application->add(new \Royal\InitCommand\GenerateControllerCommand());
$application->add(new \Royal\InitCommand\GeneratePluginCommand());
$application->add(new \Royal\InitCommand\GenerateModelCommand());
$application->run();

