<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="format-detection" content="telephone=no"/>
	<meta name="screen-orientation" content="portrait">
	<title>二哲 - Vue构建多页项目</title>
	<link rel="stylesheet" href="/public/dist/css/home/index-abb5a2b50d.css">
</head>
<body>
<div id="container">
	<my-head></my-head>
	<loading></loading>
	<index-info></index-info>
	<div id="kodo" v-tap="{methods : sayHi}" >打开控制台,看netWork 我是异步加载的js模块</div>
</div>
<script src="/public/dist/js/lib/vue-7de83fee84.js"></script>
<script src="/public/dist/js/home/index-2288fcc222.js"></script>
</body>
</html>