<?php
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>o_app 目录</title>
<script src="/public/bower_components/jquery/dist/jquery.min.js" type="text/javascript"></script>
<script src="/public/bundle.js"></script>
</head>
<body>
<input type="button" id="btn" value="按钮">
<script type="application/javascript">
    $(function () {
        $('#btn').on('click',function () {
            var url = 'http://up-cb.img-cn-qingdao.aliyuncs.com/adir/MzeF8YaKwB.jpg@_10q.png%7Cwatermark=1&&object=d2F0ZXIvMTAucG5nQDYxUA==&t=75&p=5&voffset=07'

            var patt = new RegExp('.jpg|.png|.gif|.jpeg','gi');
            var ret_test = '&'+patt.exec(url);
            url += ret_test

//            var a = document.createElement('a');
//            a.href = url;
//            a.download = "output.png";
//            document.body.appendChild(a);
//            a.click();
//            document.body.removeChild(a);

            var a = $("<a>")
                .attr("href", url)
                .attr("download", "img.png")  //命名貌似没用
                .appendTo("body");
                a[0].click();
                a.remove();
        })
    })
</script>
</body>
</html>
