<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="format-detection" content="telephone=no"/>
	<meta name="screen-orientation" content="portrait">
	<title>二哲 - vue多页项目构建</title>
	<link rel="stylesheet" href="/public/dist/css/shopping/buy-907176ff76.css">
</head>
<body>
<h3 id="buy">我是buy全局样式</h3>
<div id="container">
	<list></list>
	<loading></loading>
</div>
<script src="/public/dist/js/lib/vue-7de83fee84.js"></script>
<script src="/public/dist/js/shopping/buy-6edec8567e.js"></script>
</body>
</html>