<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>info - Vue Webpack Example</title>
    
  <link href="public/dist/css/vendors.css" rel="stylesheet"><link href="public/dist/css/another/index.css" rel="stylesheet"><link href="public/dist/css/index/index.css" rel="stylesheet"></head>
  <body>
    <p>info page</p>
    
  <script type="text/javascript" src="public/dist/js/vendors.e9e5981d960a0327d136.js"></script><script type="text/javascript" src="public/dist/js/another/index.e9e5981d960a0327d136.js"></script><script type="text/javascript" src="public/dist/js/index/index.e9e5981d960a0327d136.js"></script></body>
</html>