<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="format-detection" content="telephone=no"/>
	<meta name="screen-orientation" content="portrait">
	<title>二哲 - vue版多页应用架构</title>
</head>
<body>
<div id="container">
	<my-head></my-head>
</div>
<script src="/public/dist/js/lib/vue-7de83fee84.js"></script>
<script src="/public/dist/js/home/test-970006ab16.js"></script>
</body>
</html>